/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herencia.vista;

import herencia.controlador.controlador_polimorfismo;

/**
 *
 * @author Tarde
 */
public class vista_polimorfismo extends javax.swing.JFrame {

    /**
     * Creates new form vista_polimorfismo
     */
    public vista_polimorfismo() {
        initComponents();
        controlador_polimorfismo controlador= new controlador_polimorfismo(area1,area2,boton1,boton2,input1,input2,compra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        input1 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        compra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 180));

        area2.setColumns(20);
        area2.setRows(5);
        jScrollPane2.setViewportView(area2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 340, 180));

        boton1.setText("comprar Libros");
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, 30));

        boton2.setText("Comprar Periodicos");
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 240, 140, 30));
        getContentPane().add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, -1));
        getContentPane().add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 310, -1));

        compra.setText("jLabel1");
        getContentPane().add(compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_polimorfismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_polimorfismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_polimorfismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_polimorfismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_polimorfismo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea area1;
    public javax.swing.JTextArea area2;
    public javax.swing.JButton boton1;
    public javax.swing.JButton boton2;
    public javax.swing.JLabel compra;
    public javax.swing.JTextField input1;
    public javax.swing.JTextField input2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
